### ISSUE TITLE
On startup, sometimes the programs will shut themselves down or not respond until a restart

### ISSUE THREAD

**Issue by a-ehlinger** [anubiscapstone/robobase#2]
Sometimes when the robot is powered up, the anubiscon and videocon binaries will turn themselves off or go into an unresponsive state until restarted.  This needs investigated.

**Comment by TSmithONU** [comment]
Matt Hunter did that code. He might be able to help

**Comment by anubiscapstone** [comment]
It seems that the three issues here are separate.  #4, #5, #6
